-- AddUsageFields
ALTER TABLE "Usage" ADD COLUMN IF NOT EXISTS "provider" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Usage" ADD COLUMN IF NOT EXISTS "model" TEXT;
ALTER TABLE "Usage" ALTER COLUMN "inputTokens" SET DEFAULT 0;
ALTER TABLE "Usage" ALTER COLUMN "outputTokens" SET DEFAULT 0;
ALTER TABLE "Usage" ALTER COLUMN "cost" SET DEFAULT 0;
ALTER TABLE "Usage" ALTER COLUMN "latency" SET DEFAULT 0;
ALTER TABLE "Usage" ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT 'success';
ALTER TABLE "Usage" ADD COLUMN IF NOT EXISTS "errorMessage" TEXT;
ALTER TABLE "Usage" ADD COLUMN IF NOT EXISTS "conversationId" TEXT;